name: db apply

env:
  TZ: Asia/Shanghai

on:
  workflow_dispatch:
    inputs:
      env:
        description: target env
        required: true
        type: choice
        options: [alpha, prod]

concurrency:
  group: db-apply-${{ inputs.env }}
  cancel-in-progress: false

jobs:
  run:
    uses: ./.github/workflows/cron.yml
    with:
      name: db_apply
      env: ${{ inputs.env }}
    secrets: inherit
